services:
  api:
#    image: api
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ConnectionStrings__Postgres: ${ASPNETCORE_ConnectionStrings__Postgres}
      ASPNETCORE_Flespi__Username: ${ASPNETCORE_Flespi__Username}
      
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: climate_ctrl
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_SCHEMA: public